# Generated by Django 3.2.4 on 2021-08-27 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_pokes_userpoked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokes',
            name='userpoked',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='poked', to='main.user'),
        ),
    ]
